//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaMoneyer.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Accounts")]
    public partial class Account : Entity<string>, Base.IAuditable
    {
        public Account()
        {
            this.Transactions = new HashSet<Transaction>();
        }

        public string ProjectId { get; set; }
        public string AccountTitle { get; set; }
        public string AccountDescription { get; set; }
        public string HighlightColor { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime OpenDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public System.DateTime CreatedDate { get; set; }

        public virtual ICollection<Transaction> Transactions { get; set; }
        [ForeignKey("ProjectId")]
        public virtual Project Project {get; set;}
    }
}
