//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaMoneyer.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Categories")]
    public partial class Category : Entity<string>, Base.IAuditable
    {
        public Category()
        {
            this.Transactions = new HashSet<Transaction>();
            this.CategoryBudgets = new HashSet<CategoryBudget>();
        }

        public string ProjectId { get; set; }
        public string ParentId { get; set; }
        public string CategoryTitle { get; set; }
        public string CategoryDescription { get; set; }
        public string HighlightColor { get; set; }
        public Nullable<bool> IsIncome { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }

        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<CategoryBudget> CategoryBudgets { get; set; }

        [ForeignKey("ProjectId")]
        public virtual Project Project { get; set; }

        [ForeignKey("ParentId")]
        public virtual Category Parent { get; set; }

    }
}
