//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaMoneyer.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ProjectMembers")]
    public partial class ProjectMember : Entity<string>, Base.IAuditable
    {
        public ProjectMember()
        {
        }

        public string ProjectId { get; set; }
        public string ClientId { get; set; }

        public Nullable<int> PermissionId { get; set; }
        public string HighlightColor { get; set; }
        public bool IsArchived { get; set; }
        public bool IsFollowing { get; set; }
        public bool IsFavorite { get; set; }
	    public int? ViewFilterByType { get; set; }
        public string ViewFilterByAccount { get; set; }
	    public string ViewFilterByCategory { get; set; }

        public Nullable<System.DateTime> ViewFilterFromDate { get; set; }
        public Nullable<System.DateTime> ViewFilterEndDate { get; set; }

        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }

        public virtual Project Project { get; set; }
        public virtual Client Client { get; set; }
    }
}
