//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaMoneyer.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TimeFrequencies")]
    public partial class TimeFrequency:Entity<int>
    {
        public TimeFrequency()
        {
            this.ScheduledTransations = new HashSet<RecurringTransaction>();
        }

        public string TimeFrequencyTitle { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<byte> Weeks { get; set; }
        public int SortOrder { get; set; }

        public virtual ICollection<RecurringTransaction> ScheduledTransations { get; set; }
    }
}
