//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaMoneyer.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Transactions")]
    public partial class Transaction : Entity<string>, Base.IAuditable
    {
        public Transaction()
        {
        }

        public string TransactionTitle { get; set; }
        public string TransactionDesc { get; set; }
        public string ProjectId { get; set; }
        public string AccountId { get; set; }
        public string CategoryId { get; set; }
        public string RecurringTransactionId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public decimal Amount { get; set; }
        public Nullable<bool> IsIncome { get; set; }
        public string Payee { get; set; }
        public Nullable<bool> IsClear { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ClientId { get; set; }
        public System.DateTime CreatedDate { get; set; }

        [ForeignKey("ProjectId")]
        public virtual Project Project { get; set; }
        [ForeignKey("RecurringTransactionId")]
        public virtual RecurringTransaction RecurringTransaction { get; set; }
        [ForeignKey("CategoryId")]
        public virtual Category Category { get; set; }
        [ForeignKey("AccountId")]
        public virtual Account Account { get; set; }

        [ForeignKey("ClientId")]
        public virtual Client Client { get; set; }

    }
}
